with seed_products (
    sku,
    slug,
    name,
    description,
    category,
    category_slug,
    provider,
    price_cents,
    duration_days,
    fulfillment_notes,
    image_url
) as (
    values
        ('TPM-NETFLIX-001', 'netflix', 'Netflix Premium', 'Acesso streaming com entrega por credencial.', 'STREAMING', 'streaming', 'NETFLIX', 999, 30, 'Perfil streaming com duracao inicial de 30 dias para operacao local.', '/catalog/products/netflix.png'),
        ('TPM-CRUNCHYROLL-001', 'crunchyroll', 'Crunchyroll', 'Streaming de anime com entrega por credencial individual.', 'STREAMING', 'streaming', 'CRUNCHYROLL', 999, 30, 'Acesso streaming com vigencia operacional inicial de 30 dias.', '/catalog/products/cruchyroll.png'),
        ('TPM-AMAZON-PRIME-001', 'amazon-prime', 'Amazon Prime Video', 'Streaming com foco em filmes e series, entregue por credencial.', 'STREAMING', 'streaming', 'AMAZON_PRIME', 999, 30, 'Entrega por credencial com operacao padrao de 30 dias.', '/catalog/products/prime.png'),
        ('TPM-HULU-001', 'hulu', 'Hulu', 'Streaming com entrega por credencial e uso operacional controlado.', 'STREAMING', 'streaming', 'HULU', 999, 30, 'Entrega por credencial com operacao inicial de 30 dias.', '/catalog/products/hulu.png'),
        ('TPM-NBA-001', 'nba-league-pass', 'NBA League Pass', 'Acesso streaming esportivo com entrega por credencial.', 'STREAMING', 'streaming', 'NBA', 999, 30, 'Entrega por credencial com vigencia inicial de 30 dias.', '/catalog/products/nba.png'),
        ('TPM-PARAMOUNT-001', 'paramount-plus', 'Paramount+', 'Catalogo streaming focado em series e filmes.', 'STREAMING', 'streaming', 'PARAMOUNT_PLUS', 999, 30, 'Entrega por credencial com uso regional BR.', '/catalog/products/paramount.png'),
        ('TPM-DISNEY-001', 'disney-plus', 'Disney+', 'Streaming familiar com franquias e catalogo infantil.', 'STREAMING', 'streaming', 'DISNEY_PLUS', 999, 30, 'Entrega individual por credencial com vigencia operacional de 30 dias.', '/catalog/products/disney.png'),
        ('TPM-YOUTUBE-001', 'youtube-premium', 'YouTube Premium', 'Assinatura de video premium com entrega por credencial.', 'STREAMING', 'streaming', 'YOUTUBE_PREMIUM', 1299, 30, 'Entrega por credencial com operacao inicial de 30 dias.', '/catalog/products/youtube.png'),
        ('TPM-SPOTIFY-001', 'spotify-premium', 'Spotify Premium', 'Streaming de musica com recursos premium.', 'STREAMING', 'streaming', 'SPOTIFY', 999, 30, 'Entrega por credencial com vigencia operacional de 30 dias.', '/catalog/products/spotify.png'),
        ('TPM-TWITCH-001', 'twitch-premium', 'Twitch Premium', 'Acesso digital para comunidade, lives e beneficios premium.', 'STREAMING', 'streaming', 'TWITCH', 999, 30, 'Entrega por credencial com uso regional BR.', '/catalog/products/twicth.png'),

        ('TPM-CANVA-001', 'canva-pro', 'Canva Pro', 'Ferramenta criativa com acesso por credencial para uso recorrente.', 'ASSINATURA', 'assinaturas-premium', 'CANVA', 699, 30, 'Licenca operacional via credencial compartilhada controlada.', '/catalog/products/canva.png'),
        ('TPM-FIGMA-001', 'figma', 'Figma', 'Ferramenta de design colaborativo entregue por credencial.', 'ASSINATURA', 'assinaturas-premium', 'FIGMA', 2299, 30, 'Acesso por credencial com vigencia inicial de 30 dias.', '/catalog/products/Figma.png'),
        ('TPM-NOTION-001', 'notion-plus', 'Notion Plus', 'Workspace premium para notas, projetos e documentos.', 'ASSINATURA', 'assinaturas-premium', 'NOTION', 1299, 30, 'Entrega por credencial com uso individual.', '/catalog/products/notion.png'),
        ('TPM-DROPBOX-001', 'dropbox-plus', 'Dropbox Plus', 'Armazenamento em nuvem com recursos premium.', 'ASSINATURA', 'assinaturas-premium', 'DROPBOX', 1499, 30, 'Entrega por credencial com vigencia operacional de 30 dias.', '/catalog/products/dropbox.png'),
        ('TPM-GDRIVE-001', 'google-drive', 'Google Drive', 'Acesso digital para armazenamento e produtividade em nuvem.', 'ASSINATURA', 'assinaturas-premium', 'GOOGLE_DRIVE', 1299, 30, 'Entrega por credencial com orientacao de uso individual.', '/catalog/products/googledrive.png'),

        ('TPM-CHATGPT-001', 'chatgpt-plus', 'ChatGPT Plus', 'Acesso premium de IA com entrega por credencial.', 'ASSINATURA', 'inteligencia-artificial', 'CHATGPT_PLUS', 2599, 30, 'Entrega por credencial com orientacao de uso individual.', '/catalog/products/gpt.png'),
        ('TPM-COPILOT-001', 'copilot-pro', 'Copilot Pro', 'Acesso premium de IA para produtividade e assistencia digital.', 'ASSINATURA', 'inteligencia-artificial', 'COPILOT', 2599, 30, 'Entrega por credencial com orientacao de uso individual.', '/catalog/products/copilot.png'),
        ('TPM-MIDJOURNEY-001', 'midjourney', 'Midjourney', 'Acesso a geracao de imagens por IA.', 'ASSINATURA', 'inteligencia-artificial', 'MIDJOURNEY', 2999, 30, 'Entrega por credencial com vigencia operacional de 30 dias.', '/catalog/products/midjourney.png'),
        ('TPM-CLAUDE-001', 'claude-pro', 'Claude Pro', 'Acesso premium de IA para escrita, pesquisa e produtividade.', 'ASSINATURA', 'inteligencia-artificial', 'CLAUDE', 2599, 30, 'Entrega por credencial com orientacao de uso individual.', '/catalog/products/claude.png'),

        ('TPM-ADOBE-001', 'adobe-creative-cloud', 'Adobe Creative Cloud', 'Acesso premium para ferramentas criativas e edicao.', 'ASSINATURA', 'softwares-licencas', 'ADOBE', 2499, 30, 'Entrega por credencial com orientacao de uso individual.', '/catalog/products/adobe.png'),
        ('TPM-CAPCUT-001', 'capcut-pro', 'CapCut Pro', 'Assinatura para edicao de videos e recursos premium.', 'ASSINATURA', 'softwares-licencas', 'CAPCUT', 1499, 30, 'Entrega por credencial com vigencia operacional de 30 dias.', '/catalog/products/capcut.png'),
        ('TPM-GITHUB-001', 'github-pro', 'GitHub Pro', 'Acesso premium para desenvolvimento e repositorios.', 'ASSINATURA', 'softwares-licencas', 'GITHUB', 1999, 30, 'Entrega por credencial com uso individual.', '/catalog/products/github.png'),
        ('TPM-VSCODE-001', 'vscode-tools', 'VS Code Tools', 'Pacote digital para produtividade e desenvolvimento.', 'ASSINATURA', 'softwares-licencas', 'VSCODE', 999, 30, 'Entrega por credencial ou instrucoes operacionais.', '/catalog/products/vscode.png'),

        ('TPM-STEAM-001', 'steam', 'Steam', 'Conta ou credito digital para plataforma de jogos.', 'GAMES', 'games', 'STEAM', 1999, 0, 'Entrega de acesso digital com instrucoes operacionais.', '/catalog/products/steam.png'),
        ('TPM-XBOX-001', 'xbox', 'Xbox', 'Produto digital para jogos, conta ou beneficios Xbox.', 'GAMES', 'games', 'XBOX', 1999, 0, 'Entrega de acesso digital com instrucoes operacionais.', '/catalog/products/xbox.png'),
        ('TPM-ROBLOX-001', 'roblox', 'Roblox', 'Produto digital para conta, creditos ou beneficios Roblox.', 'GAMES', 'games', 'ROBLOX', 1499, 0, 'Entrega de acesso digital com instrucoes operacionais.', '/catalog/products/roblox.png'),
        ('TPM-NINTENDO-001', 'nintendo', 'Nintendo', 'Produto digital para conta, jogos ou beneficios Nintendo.', 'GAMES', 'games', 'NINTENDO', 1999, 0, 'Entrega de acesso digital com instrucoes operacionais.', '/catalog/products/nintendp.png'),
        ('TPM-LOL-D1-001', 'lol-diamante-1', 'Conta LoL Diamante 1', 'Conta de League of Legends pronta para uso em tier Diamante 1.', 'GAMES', 'games', 'LEAGUE_OF_LEGENDS', 24990, 0, 'Entrega de conta individual com troca imediata de acesso recomendada.', '/catalog/products/lol.png'),
        ('TPM-LOL-P2-001', 'lol-platina-2', 'Conta LoL Platina 2', 'Conta de League of Legends pronta para uso em tier Platina 2.', 'GAMES', 'games', 'LEAGUE_OF_LEGENDS', 15890, 0, 'Entrega de conta individual com troca imediata de acesso recomendada.', '/catalog/products/lol.png'),
        ('TPM-LOL-CHALL-001', 'lol-desafiante', 'Conta LoL Desafiante', 'Conta de League of Legends pronta para uso em tier Desafiante.', 'GAMES', 'games', 'LEAGUE_OF_LEGENDS', 38999, 0, 'Entrega de conta individual com prioridade operacional.', '/catalog/products/lol.png'),
        ('TPM-LOL-FERRO-001', 'lol-ferro', 'Conta LoL Ferro', 'Conta de League of Legends pronta para uso em tier Ferro.', 'GAMES', 'games', 'LEAGUE_OF_LEGENDS', 5990, 0, 'Entrega de conta individual com troca imediata de acesso recomendada.', '/catalog/products/lol.png'),
        ('TPM-LOL-BRONZE-001', 'lol-bronze', 'Conta LoL Bronze', 'Conta de League of Legends pronta para uso em tier Bronze.', 'GAMES', 'games', 'LEAGUE_OF_LEGENDS', 7990, 0, 'Entrega de conta individual com troca imediata de acesso recomendada.', '/catalog/products/lol.png'),
        ('TPM-LOL-PRATA-001', 'lol-prata', 'Conta LoL Prata', 'Conta de League of Legends pronta para uso em tier Prata.', 'GAMES', 'games', 'LEAGUE_OF_LEGENDS', 9990, 0, 'Entrega de conta individual com troca imediata de acesso recomendada.', '/catalog/products/lol.png'),
        ('TPM-LOL-OURO-001', 'lol-ouro', 'Conta LoL Ouro', 'Conta de League of Legends pronta para uso em tier Ouro.', 'GAMES', 'games', 'LEAGUE_OF_LEGENDS', 12990, 0, 'Entrega de conta individual com troca imediata de acesso recomendada.', '/catalog/products/lol.png'),
        ('TPM-LOL-ESMERALDA-001', 'lol-esmeralda', 'Conta LoL Esmeralda', 'Conta de League of Legends pronta para uso em tier Esmeralda.', 'GAMES', 'games', 'LEAGUE_OF_LEGENDS', 18990, 0, 'Entrega de conta individual com troca imediata de acesso recomendada.', '/catalog/products/lol.png'),
        ('TPM-LOL-MESTRE-001', 'lol-mestre', 'Conta LoL Mestre', 'Conta de League of Legends pronta para uso em tier Mestre.', 'GAMES', 'games', 'LEAGUE_OF_LEGENDS', 44990, 0, 'Entrega de conta individual com prioridade operacional.', '/catalog/products/lol.png'),

        ('TPM-DISCORD-001', 'discord-nitro', 'Discord Nitro', 'Acesso premium para comunidade, chamadas e recursos sociais.', 'ASSINATURA', 'redes-sociais', 'DISCORD', 1499, 30, 'Entrega por credencial com vigencia operacional de 30 dias.', '/catalog/products/discord.png'),
        ('TPM-INSTAGRAM-001', 'instagram', 'Instagram', 'Servico digital para perfil e operacao em rede social.', 'ASSINATURA', 'redes-sociais', 'INSTAGRAM', 999, 30, 'Entrega conforme instrucoes operacionais do servico.', '/catalog/products/instagrram.png'),
        ('TPM-LINKEDIN-001', 'linkedin-premium', 'LinkedIn Premium', 'Acesso premium para networking e carreira.', 'ASSINATURA', 'redes-sociais', 'LINKEDIN', 1999, 30, 'Entrega por credencial com vigencia operacional de 30 dias.', '/catalog/products/linkedin.png'),
        ('TPM-PINTEREST-001', 'pinterest', 'Pinterest', 'Servico digital para perfil e operacao em rede social.', 'ASSINATURA', 'redes-sociais', 'PINTEREST', 999, 30, 'Entrega conforme instrucoes operacionais do servico.', '/catalog/products/pinterest.png'),
        ('TPM-REDDIT-001', 'reddit-premium', 'Reddit Premium', 'Acesso premium e beneficios para comunidade digital.', 'ASSINATURA', 'redes-sociais', 'REDDIT', 999, 30, 'Entrega por credencial com vigencia operacional de 30 dias.', '/catalog/products/reddit.png'),
        ('TPM-SNAPCHAT-001', 'snapchat-plus', 'Snapchat+', 'Acesso premium para rede social e recursos extras.', 'ASSINATURA', 'redes-sociais', 'SNAPCHAT', 999, 30, 'Entrega por credencial com vigencia operacional de 30 dias.', '/catalog/products/snapchat.png'),
        ('TPM-TELEGRAM-001', 'telegram-premium', 'Telegram Premium', 'Acesso premium para mensagens, arquivos e comunidade.', 'ASSINATURA', 'redes-sociais', 'TELEGRAM', 999, 30, 'Entrega por credencial com vigencia operacional de 30 dias.', '/catalog/products/telegram.png'),
        ('TPM-TIKTOK-001', 'tiktok', 'TikTok', 'Servico digital para perfil e operacao em rede social.', 'ASSINATURA', 'redes-sociais', 'TIKTOK', 999, 30, 'Entrega conforme instrucoes operacionais do servico.', '/catalog/products/tiktok.png'),
        ('TPM-WHATSAPP-001', 'whatsapp-business', 'WhatsApp Business', 'Servico digital para conta, atendimento e operacao.', 'ASSINATURA', 'redes-sociais', 'WHATSAPP', 999, 30, 'Entrega conforme instrucoes operacionais do servico.', '/catalog/products/whatsapp.png'),
        ('TPM-X-001', 'x-premium', 'X Premium', 'Acesso premium para rede social X.', 'ASSINATURA', 'redes-sociais', 'X', 1499, 30, 'Entrega por credencial com vigencia operacional de 30 dias.', '/catalog/products/x.png'),

        ('TPM-DUOLINGO-001', 'duolingo-super', 'Duolingo Super', 'Acesso premium para estudos e pratica de idiomas.', 'ASSINATURA', 'cursos-treinamentos', 'DUOLINGO', 999, 30, 'Entrega por credencial com vigencia operacional de 30 dias.', '/catalog/products/duolinguo.png'),
        ('TPM-ICLOUD-001', 'icloud-plus', 'iCloud+', 'Armazenamento e recursos premium para conta digital.', 'ASSINATURA', 'contas-digitais', 'ICLOUD', 1299, 30, 'Entrega por credencial com vigencia operacional de 30 dias.', '/catalog/products/icloud.png'),
        ('TPM-PAYPAL-001', 'paypal', 'PayPal', 'Conta digital ou servico operacional para pagamentos.', 'ASSINATURA', 'contas-digitais', 'PAYPAL', 1499, 30, 'Entrega conforme instrucoes operacionais do servico.', '/catalog/products/paypal.png'),
        ('TPM-TEKNISA-001', 'teknisa', 'Teknisa', 'Acesso digital para software e operacao profissional.', 'ASSINATURA', 'servicos-digitais', 'TEKNISA', 1999, 30, 'Entrega por credencial com vigencia operacional de 30 dias.', '/catalog/products/teknisa.png')
)
insert into products (
    id,
    sku,
    slug,
    name,
    description,
    image_url,
    category_id,
    category,
    provider,
    status,
    price_cents,
    currency,
    region_code,
    duration_days,
    delivery_type,
    requires_stock,
    fulfillment_notes,
    created_at,
    updated_at
)
select
    gen_random_uuid(),
    seed_products.sku,
    seed_products.slug,
    seed_products.name,
    seed_products.description,
    seed_products.image_url,
    catalog_categories.id,
    seed_products.category,
    seed_products.provider,
    'ACTIVE',
    seed_products.price_cents,
    'BRL',
    'BR',
    seed_products.duration_days,
    'CREDENTIAL',
    true,
    seed_products.fulfillment_notes,
    now(),
    now()
from seed_products
join catalog_categories on catalog_categories.slug = seed_products.category_slug
on conflict (sku) do update set
    slug = excluded.slug,
    name = excluded.name,
    description = excluded.description,
    image_url = excluded.image_url,
    category_id = excluded.category_id,
    category = excluded.category,
    provider = excluded.provider,
    status = excluded.status,
    price_cents = excluded.price_cents,
    currency = excluded.currency,
    region_code = excluded.region_code,
    duration_days = excluded.duration_days,
    delivery_type = excluded.delivery_type,
    requires_stock = excluded.requires_stock,
    fulfillment_notes = excluded.fulfillment_notes,
    updated_at = now();
